### PR TITLE
Replace custom serialization methods with pickle

### PR DESCRIPTION
**Pull request by OCHyams**
The goal of this change is to reduce the maintenance overhead and code
complexity by removing the custom serialization.

This breaks python2 compatibility, which is okay because this is a part of
#10.

Instead of serialising everything to json the standard pickle module is used.
Because pickle is a standard library we don't need to test it!

Having a standard text format for output is an important feature; this
will be added back in another PR.

I imagine there will be conflicts with some of the other PRs, especially #13 and #10.
These can be addressed after those two important PRs have been accepted.

### CODE REVIEW

**Comment by OCHyams** [comment]
Note: "Having a standard text format for output is an important feature" may not necessarily be true. There is already a 'view' tool to display the files for humans and adding another output format that can be consumed by non-python programs isn't required right now.

**Comment by Melamoto** [comment]
Also, #10 and #13 have been merged, so this can be reapplied from there.

**Comment by TomWeaver18** [comment]
LGTM, loving how much was cut out with this patch.

**Comment by OCHyams** [comment]
Rebased

**Comment by OCHyams** [comment]
Rebased again. This time without introducing runtime errors.

**Comment by OCHyams** [comment]
Rebased and squashed

**Pull request merged**
